---
title: "Visualizations"
author: "Grace Lewin"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(here)
library(leaflet)
library(leafem)
library(RColorBrewer)
library(sf)
```



```{r}
# #read in metabarcoding data, select only relevant columns (can select diff columns for diff analyses)
# gaviota <- read_csv(here("metabarcoding_scripts_GL", "gaviota.csv")) |>
#   select(LabID, ScatID, curated_species, common_name, broadtax, broadtax1, host, site, guessed_sp, target)
# 
# # read in the data file containing coordinates. This is the file from the field collection. From Survey123.
# coords <- read_csv(here("data", "scat_data6.11.24.correcteddateformat.csv")) |>
#   select(ScatID, lon, lat)
# 
# # join datasets by ScatID
# gaviota <- left_join(gaviota, coords, by = "ScatID")
# 
# write_csv(gaviota, file = "gaviota_with_coordinates.csv")

gaviota <- read_csv(here("metabarcoding_scripts_GL", "outputs", "gaviota_with_coordinates.csv"))
```


Display a map

```{r}
# species_colors <- c(
#   coyote = "red",
#   bobcat = "blue",
#   bear = "green",
#   deer = "orange",
#   `wild pig` = "purple",
#   fox = "pink",
#   puma = "brown",
#   unknown = "gray"
# )

factpal <- colorFactor(rainbow(8), gaviota$broadtax)

lopt = labelOptions(noHide = TRUE,
                    direction = 'top',
                    textOnly = TRUE)

# Create the leaflet map with point color
map <- leaflet(gaviota) |> 
  addTiles() |>   # Add default OpenStreetMap tiles
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = 1,
    opacity = .5,
    color = ~factpal(broadtax),
    popup = ~ScatID) |> 
  addLegend(
    "bottomright",  # Legend position
    pal = factpal,  # Color palette
    values = ~broadtax,  # Values to display in legend
    title = "Species",  # Legend title
    opacity = 1  # Adjust legend opacity
  )

# Display the map
map
```



Map for just Dangermond target sites (the target species collected)

```{r}
target_dangermond_gaviota <- gaviota |> 
  filter(site == "Dangermond",
         target == "target")

preserve_boundary <- st_read(here("data", "jldp_boundary_316755993546447087.geojson"))


#host != c("Puma", "Coyote", "Bobcat","Mule deer", 'Wild boar')

# species_colors <- c(
#   coyote = "red",
#   bobcat = "blue",
#   bear = "green",
#   deer = "orange",
#   `wild pig` = "purple",
#   fox = "pink",
#   puma = "brown",
#   unknown = "gray"
# )

# Define a color palette based on 'broadtax'
colorpal <- colorFactor(
  palette = brewer.pal(5, "Dark2"),
  domain = target_dangermond_gaviota$broadtax
)

map1 <- leaflet(target_dangermond_gaviota) |> 
  addProviderTiles("CartoDB.Positron") |>   
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = 1,  # Bigger radius for visibility
    opacity = 0.7,
    fillOpacity = 0.7,
    color = ~colorpal(broadtax),  # assign colors by broadtax
    popup = ~ScatID
  ) |> 
  addPolygons(
    data = preserve_boundary,
    fillColor = "transparent",   # transparent fill
    color = "red",                # red boundary line
    weight = 2,                   # line thickness
    opacity = 1,
    label = "Preserve Boundary") |> 
  addLegend(
    position = "bottomright",
    pal = colorpal,
    values = ~broadtax,
    title = "Species",
    opacity = 1
  )

map1
```

EH samples at Dangermond 

```{r}
EH_pig_samples <- gaviota |> 
  filter(SampleSet == "EH")

map_EH_pig_samples <- leaflet(EH_pig_samples)|> 
  addPolygons(
    data = preserve_boundary,
    fillColor = "transparent",   # transparent fill
    color = "red",                # red boundary line
    weight = 2,                   # line thickness
    opacity = 1,
    label = "Preserve Boundary") |> 
  addLegend(
    position = "bottomright",
    pal = colorpal,
    values = ~broadtax,
    title = "Species",
    opacity = 1
  ) |> 
  addProviderTiles("CartoDB.Positron") |>   
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = 1,  # Bigger radius for visibility
    opacity = 0.7,
    fillOpacity = 0.7,
    color = ~colorpal(broadtax),  # assign colors by broadtax
    popup = ~paste0("LabID: ", LabID, "<br>ScatID: ", ScatID, "<br>host: ", host)
  ) 

map_EH_pig_samples
```





Just coyote at Dangermond

```{r}
coyote_dangermond_gaviota <- gaviota |> 
  filter(site == "Dangermond",
         )


# species_colors <- c(
#   coyote = "red",
#   bobcat = "blue",
#   bear = "green",
#   deer = "orange",
#   `wild pig` = "purple",
#   fox = "pink",
#   puma = "brown",
#   unknown = "gray"
# )

factpal <- colorFactor(rainbow(8), gaviota$broadtax)

lopt = labelOptions(noHide = TRUE,
                    direction = 'top',
                    textOnly = TRUE)

# Create the leaflet map with point color
map <- leaflet(gaviota) |> 
  addTiles() |>   # Add default OpenStreetMap tiles
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat,
    radius = 1,
    opacity = .5,
    color = ~factpal(broadtax),
    popup = ~ScatID) |> 
  addLegend(
    "bottomright",  # Legend position
    pal = factpal,  # Color palette
    values = ~broadtax,  # Values to display in legend
    title = "Species",  # Legend title
    opacity = 1  # Adjust legend opacity
  )

# Display the map
map
```


Histogram of samples of each target species collected at Dangermond
```{r}
target_dangermond_gaviota <- target_dangermond_gaviota |> 
  mutate(broadtax = forcats::fct_infreq(broadtax))

# Build the bar chart
hist <- ggplot(target_dangermond_gaviota, aes(x = broadtax, fill = broadtax)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +  # <<< ADD NUMBERS
  scale_fill_manual(values = colorpal(levels(target_dangermond_gaviota$broadtax))) +
  labs(
    title = "Scat Samples of 5 Target Species Found at Dangermond",
    x = "Species",
    y = "Count"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

# Display the histogram
hist
```




